name: Test

on:
  workflow_dispatch:
    inputs:
      json:
        required: true
        type: string

jobs:

  foo:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        msg: ${{ fromJson(inputs.json).*.arr.*.msg }}

    steps:
      - shell: bash
        run: echo "${msg}"
        env:
          msg: ${{ matrix.msg }}
