name: Test

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test.yml

jobs:

  foo:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - shell: bash
        run: echo "BAR=BAZ" >> ${GITHUB_ENV}
        if: env.BAR != ''
        
      - shell: bash
        run: echo "BAR=QUUX" >> ${GITHUB_ENV}
        if: env.BAR != ''

      - shell: bash
        run: echo ${BAR}
